### ISSUE TITLE
Bruh imagine leaking

### ISSUE THREAD

**Issue by billythegoat356** [aceeontop/wasp-stealer#1]
bro must be jealous 💀

**Comment by aceeontop** [comment]
stay mad bro

**Comment by billythegoat356** [comment]
huh why would I be mad ? you have 1 star and 1 follower. cmon bro don't be ridiculous I don't give a shit about you leaking wasp

**Comment by aceeontop** [comment]
LOL bro thinks i care abt stars keep coping

**Comment by billythegoat356** [comment]
stars = popularity
if you have 0 stars it means nobody checks your project
are you dumb or smth?

**Comment by aceeontop** [comment]
my honest reaction 😐

**Comment by 97FaceR** [comment]
@aceeontop can u add injection?

**Comment by tEMMIE6823** [comment]
Mashallah brother
